name: build-action

on:
  push:
    branches:
      - 'dev'
jobs:
  reacting:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: oscarnevarezleal/laravel-installer-action:latest
      -
        run: |
          docker images
          docker run oscarnevarezleal/laravel-installer-action:latest version
          docker run oscarnevarezleal/laravel-installer-action:latest new app