name: build-action

on:
  push:
    branches:
      - 'dev'
jobs:
  reacting:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: banana

      - name: Test
        run: |
          docker images
          docker run --rm -v $(pwd):/github/workspace/ banana --version
          docker run --rm -v $(pwd):/github/workspace/ banana new app
          ls -ltah

      -
        uses: ./
        with:
          args: new build